[package]
name = "realworld-axum-sqlx"
version = "0.1.0"
edition = "2024"
publish = false
authors = [
    "Austin Bonander <austin@launchbadge.com>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Core dependencies: runtime, HTTP framework and database client.
futures = "0.3.31"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
axum = { version = "0.8.6", features = ["tower-log"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-native-tls", "postgres", "uuid", "time"] }
redis = { version = "0.32.7", features = ["tokio-comp"] }
deadpool-redis = "0.22.0"

# The `clap` beta gives us a much nicer way to define configuration parameters for our application.
clap = { version = "4.5.51", features = ["derive", "env"] }

serde = { version = "1.0.228", features = ["derive"] }

# State of the art password hashing.
argon2 = "0.5.3"

# Axum builds on the types in Tower
tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["trace", "add-extension"] }

jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.9"

time = "0.3.44"

uuid = { version = "1.18.1", features = ["serde"] }

# Utility Crates
anyhow = "1.0.48"
async-trait = "0.1.51"
dotenv = "0.15.0"
env_logger = "0.11.8"
itertools = "0.14.0"
log = "0.4.14"
rand = "0.9.2"
thiserror = "2.0.17"
serde_json = "1"

[dev-dependencies]
reqwest = { version = "0.12.24", features = ["json"] }
serde_json = "1"
testcontainers = { version = "0.25.2", features = [] }

[lib]
doctest = false

[[bin]]
name = "realworld-axum-sqlx"
doctest = false
